//https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates - Required root layout

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} 
      m-20 p-6 text-xl font-medium`}>
        {children} </body>
    </html>
  );
}
